services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: paas_minecraft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  infrared:
    image: haveachin/infrared:latest
    container_name: infrared-proxy
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./config/infrared/proxies:/proxies
      - ./config/infrared/config.yml:/config.yml:ro
    networks:
      - minecraft-network
    environment:
      - INFRARED_CONFIG=/config.yml
      - INFRARED_PROXIES_DIR=/proxies

networks:
  minecraft-network:
    driver: bridge

volumes:
  postgres_data:
