services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: paas_minecraft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
